// Geographic map of the location pages, used for "nearby areas" links.
// Each summary is drawn from what that location page itself covers, so the
// link text always matches the page it points to. When a new location page
// is added, give it an entry here and list it as a neighbor of one or two existing
// pages so it is never an orphan.

export interface LocationInfo {
  name: string; // full name, used in link text
  short: string; // used in headings
  kind: "city" | "state";
  summary: string;
}

export const locations: Record<string, LocationInfo> = {
  "new-york": { name: "New York City", short: "New York City", kind: "city", summary: "One of the largest Muslim communities in America, across all five boroughs." },
  "paterson-new-jersey": { name: "Paterson, New Jersey", short: "Paterson", kind: "city", summary: "Home to one of the country's largest Arab American communities in North Jersey." },
  philadelphia: { name: "Philadelphia, Pennsylvania", short: "Philadelphia", kind: "city", summary: "A city with deep roots in American Muslim history." },
  delaware: { name: "Delaware", short: "Delaware", kind: "state", summary: "Classes for families across the state, including Wilmington." },
  "baltimore-maryland": { name: "Baltimore, Maryland", short: "Baltimore", kind: "city", summary: "Home to one of America's oldest African American Muslim communities." },
  "washington-dc": { name: "Washington, D.C.", short: "Washington, D.C.", kind: "city", summary: "An established, diverse community in the nation's capital." },
  "northern-virginia": { name: "Northern Virginia", short: "Northern Virginia", kind: "city", summary: "Home to one of America's largest Afghan American communities." },
  "west-virginia": { name: "West Virginia", short: "West Virginia", kind: "state", summary: "Classes for families across the state, including Charleston." },
  boston: { name: "Boston, Massachusetts", short: "Boston", kind: "city", summary: "A diverse, academic community across Greater Boston." },
  "providence-rhode-island": { name: "Providence, Rhode Island", short: "Providence", kind: "city", summary: "A compact community in America's smallest state." },
  "hartford-connecticut": { name: "Hartford, Connecticut", short: "Hartford", kind: "city", summary: "A community shaped by the city's long history as an insurance center." },
  "new-hampshire": { name: "New Hampshire", short: "New Hampshire", kind: "state", summary: "Classes for families across the state, including Manchester." },
  vermont: { name: "Vermont", short: "Vermont", kind: "state", summary: "Classes for families across the state, including Burlington." },
  maine: { name: "Maine", short: "Maine", kind: "state", summary: "Classes for families across the state, including Portland." },
  chicago: { name: "Chicago, Illinois", short: "Chicago", kind: "city", summary: "One of the five largest Muslim communities in the United States." },
  "milwaukee-wisconsin": { name: "Milwaukee, Wisconsin", short: "Milwaukee", kind: "city", summary: "A close-knit community just up the Lake Michigan shore from Chicago." },
  minneapolis: { name: "Minneapolis-St. Paul, Minnesota", short: "the Twin Cities", kind: "city", summary: "Home to one of America's largest Somali Muslim communities." },
  "dearborn-michigan": { name: "Dearborn, Michigan", short: "Dearborn", kind: "city", summary: "Often called the Arab American Muslim capital of the United States." },
  "columbus-ohio": { name: "Columbus, Ohio", short: "Columbus", kind: "city", summary: "A diverse, growing community in central Ohio." },
  "indianapolis-indiana": { name: "Indianapolis, Indiana", short: "Indianapolis", kind: "city", summary: "A growing community at the Crossroads of America." },
  "louisville-kentucky": { name: "Louisville, Kentucky", short: "Louisville", kind: "city", summary: "Muhammad Ali's hometown, with a warm and growing community." },
  "st-louis-missouri": { name: "St. Louis, Missouri", short: "St. Louis", kind: "city", summary: "Home to the largest Bosnian community outside Bosnia." },
  "nashville-tennessee": { name: "Nashville, Tennessee", short: "Nashville", kind: "city", summary: "Home to one of America's best-known Kurdish communities." },
  atlanta: { name: "Atlanta, Georgia", short: "Atlanta", kind: "city", summary: "One of the fastest-growing Muslim communities in the South." },
  "charlotte-north-carolina": { name: "Charlotte, North Carolina", short: "Charlotte", kind: "city", summary: "A young community in one of the country's fastest-growing cities." },
  "charleston-south-carolina": { name: "Charleston, South Carolina", short: "Charleston", kind: "city", summary: "A small, growing community in a historic port city." },
  "birmingham-alabama": { name: "Birmingham, Alabama", short: "Birmingham", kind: "city", summary: "A community closely tied to the city's large medical center." },
  "jackson-mississippi": { name: "Jackson, Mississippi", short: "Jackson", kind: "city", summary: "A small community where local Quran teaching options are limited." },
  "new-orleans-louisiana": { name: "New Orleans, Louisiana", short: "New Orleans", kind: "city", summary: "A small, resilient community in a city known for its hospitality." },
  "little-rock-arkansas": { name: "Little Rock, Arkansas", short: "Little Rock", kind: "city", summary: "A real community with few local Quran teaching options." },
  "miami-florida": { name: "Miami, Florida", short: "Miami", kind: "city", summary: "A global, multilingual community across South Florida." },
  houston: { name: "Houston, Texas", short: "Houston", kind: "city", summary: "A growing hub of American Muslim life, from Sugar Land to Katy." },
  dallas: { name: "Dallas, Texas", short: "Dallas", kind: "city", summary: "A fast-growing community across the Dallas and Fort Worth area." },
  "oklahoma-city": { name: "Oklahoma City, Oklahoma", short: "Oklahoma City", kind: "city", summary: "A diverse community spread across a sprawling metro." },
  "wichita-kansas": { name: "Wichita, Kansas", short: "Wichita", kind: "city", summary: "A community built around the Air Capital of the World." },
  "omaha-nebraska": { name: "Omaha, Nebraska", short: "Omaha", kind: "city", summary: "Home to a significant Sudanese and East African community." },
  "des-moines-iowa": { name: "Des Moines, Iowa", short: "Des Moines", kind: "city", summary: "A community centered in the city and spread across Iowa." },
  "north-dakota": { name: "North Dakota", short: "North Dakota", kind: "state", summary: "Classes for families across the state, including Fargo." },
  "south-dakota": { name: "South Dakota", short: "South Dakota", kind: "state", summary: "Classes for families across the state, including Sioux Falls." },
  montana: { name: "Montana", short: "Montana", kind: "state", summary: "Classes for families across the state, including Billings." },
  wyoming: { name: "Wyoming", short: "Wyoming", kind: "state", summary: "Classes for families across the state, including Cheyenne." },
  idaho: { name: "Idaho", short: "Idaho", kind: "state", summary: "Classes for families across the state, including Boise." },
  "denver-colorado": { name: "Denver, Colorado", short: "Denver", kind: "city", summary: "A community shaped by resettlement, migration and steady growth." },
  "salt-lake-city-utah": { name: "Salt Lake City, Utah", short: "Salt Lake City", kind: "city", summary: "A small, close-knit Muslim community in Utah's capital." },
  "las-vegas": { name: "Las Vegas, Nevada", short: "Las Vegas", kind: "city", summary: "A community living around a city that runs day and night." },
  "phoenix-arizona": { name: "Phoenix, Arizona", short: "Phoenix", kind: "city", summary: "A fast-growing community spread across the Valley." },
  "albuquerque-new-mexico": { name: "Albuquerque, New Mexico", short: "Albuquerque", kind: "city", summary: "A small community spread across the high desert." },
  "los-angeles": { name: "Los Angeles, California", short: "Los Angeles", kind: "city", summary: "A large Muslim presence spread across the LA metro." },
  seattle: { name: "Seattle, Washington", short: "Seattle", kind: "city", summary: "A tech-driven community with strong East African and South Asian roots." },
  "portland-oregon": { name: "Portland, Oregon", short: "Portland", kind: "city", summary: "A growing East African community that is welcoming to reverts." },
  "honolulu-hawaii": { name: "Honolulu, Hawaii", short: "Honolulu", kind: "city", summary: "A small island community thousands of miles from the mainland." },
  alaska: { name: "Alaska", short: "Alaska", kind: "state", summary: "Classes for families across the state, including Anchorage." },
};

// Neighbors are chosen by real geography (same metro, bordering state or the
// nearest covered city), or by a shared practical issue where no city is
// close, e.g. Alaska and Hawaii both schedule far from mainland time zones,
// and Miami, Houston and New Orleans all plan around hurricane season.
export const nearby: Record<string, string[]> = {
  "new-york": ["paterson-new-jersey", "philadelphia", "hartford-connecticut"],
  "paterson-new-jersey": ["new-york", "philadelphia"],
  philadelphia: ["new-york", "delaware", "baltimore-maryland"],
  delaware: ["philadelphia", "baltimore-maryland"],
  "baltimore-maryland": ["washington-dc", "northern-virginia", "philadelphia"],
  "washington-dc": ["northern-virginia", "baltimore-maryland"],
  "northern-virginia": ["washington-dc", "baltimore-maryland", "west-virginia"],
  "west-virginia": ["northern-virginia", "columbus-ohio"],
  boston: ["providence-rhode-island", "new-hampshire", "maine"],
  "providence-rhode-island": ["boston", "hartford-connecticut"],
  "hartford-connecticut": ["new-york", "providence-rhode-island", "boston"],
  "new-hampshire": ["boston", "vermont", "maine"],
  vermont: ["new-hampshire", "maine"],
  maine: ["new-hampshire", "boston"],
  chicago: ["milwaukee-wisconsin", "indianapolis-indiana", "dearborn-michigan"],
  "milwaukee-wisconsin": ["chicago", "minneapolis"],
  minneapolis: ["milwaukee-wisconsin", "north-dakota", "des-moines-iowa"],
  "dearborn-michigan": ["columbus-ohio", "chicago"],
  "columbus-ohio": ["dearborn-michigan", "indianapolis-indiana", "west-virginia"],
  "indianapolis-indiana": ["chicago", "louisville-kentucky", "columbus-ohio"],
  "louisville-kentucky": ["indianapolis-indiana", "nashville-tennessee", "st-louis-missouri"],
  "st-louis-missouri": ["chicago", "louisville-kentucky"],
  "nashville-tennessee": ["louisville-kentucky", "birmingham-alabama", "atlanta"],
  atlanta: ["birmingham-alabama", "charlotte-north-carolina", "nashville-tennessee"],
  "charlotte-north-carolina": ["charleston-south-carolina", "atlanta"],
  "charleston-south-carolina": ["charlotte-north-carolina", "atlanta"],
  "birmingham-alabama": ["atlanta", "jackson-mississippi", "nashville-tennessee"],
  "jackson-mississippi": ["birmingham-alabama", "new-orleans-louisiana", "little-rock-arkansas"],
  "new-orleans-louisiana": ["jackson-mississippi", "houston", "miami-florida"],
  "little-rock-arkansas": ["oklahoma-city", "jackson-mississippi"],
  "miami-florida": ["atlanta", "houston", "new-orleans-louisiana"],
  houston: ["dallas", "new-orleans-louisiana", "miami-florida"],
  dallas: ["houston", "oklahoma-city"],
  "oklahoma-city": ["dallas", "wichita-kansas", "little-rock-arkansas"],
  "wichita-kansas": ["oklahoma-city", "omaha-nebraska"],
  "omaha-nebraska": ["des-moines-iowa", "south-dakota", "wichita-kansas"],
  "des-moines-iowa": ["omaha-nebraska", "minneapolis"],
  "north-dakota": ["minneapolis", "south-dakota", "montana"],
  "south-dakota": ["north-dakota", "omaha-nebraska", "minneapolis"],
  montana: ["wyoming", "idaho", "north-dakota"],
  wyoming: ["denver-colorado", "montana", "salt-lake-city-utah"],
  idaho: ["salt-lake-city-utah", "montana"],
  "denver-colorado": ["wyoming", "salt-lake-city-utah", "albuquerque-new-mexico"],
  "salt-lake-city-utah": ["idaho", "denver-colorado", "las-vegas"],
  "las-vegas": ["los-angeles", "phoenix-arizona", "salt-lake-city-utah"],
  "phoenix-arizona": ["las-vegas", "albuquerque-new-mexico", "los-angeles"],
  "albuquerque-new-mexico": ["phoenix-arizona", "denver-colorado"],
  "los-angeles": ["las-vegas", "phoenix-arizona"],
  seattle: ["portland-oregon", "alaska"],
  "portland-oregon": ["seattle", "idaho"],
  "honolulu-hawaii": ["alaska", "los-angeles"],
  alaska: ["seattle", "honolulu-hawaii"],
};
